name: frogsquash
summary: Use code blocks to program your animal to follow commands
description: |
  Do you have what it takes to cross these treacherous roads? You must dodge arrows, saws, and fire balls and not get squashed! While you survive, try to amass lots of loot to unlock a menagerie of animals. Hack your animal's AI to master the roads and go farther than ever before!
version: '1.2'
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  frogsquash:
    extensions: [gnome]
    command: /FrogSquash.x86_64
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - joystick
      - network
      - opengl
      - wayland
      - x11

parts:
  frogsquash:
    source: https://github.com/endless-network/FrogSquash_Binary/releases/download/v1.2/FrogSquash.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/FrogSquash.x86_64
  desktop-files:
    plugin: nil
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui
